# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_ITV.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyeip
import time
import tkinter

hostname1 = "192.168.1.20"
hostname2 = "192.168.1.21"
hostname3 = "192.168.1.22"
EIP_1 = pyeip.EtherNetIP(hostname1)
EIP_2 = pyeip.EtherNetIP(hostname2)
EIP_3 = pyeip.EtherNetIP(hostname3)
##global C_A
##global C_B
##global C_C
C_A = 1 #defult value
C_B = 1 #defult value
C_C = 1 #defult value
high = 4095
low = 0
ITV_A_Net_Status = False
value = high

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setMinimumSize(QtCore.QSize(720, 480))
        MainWindow.setMaximumSize(QtCore.QSize(720, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(600, 10, 111, 28))
        self.btn_exit.setObjectName("btn_exit")
        self.btn_OFF = QtWidgets.QPushButton(self.centralwidget)
        self.btn_OFF.setGeometry(QtCore.QRect(400, 250, 281, 161))
        self.btn_OFF.setObjectName("btn_OFF")
        self.btn_ON = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ON.setGeometry(QtCore.QRect(40, 250, 271, 161))
        self.btn_ON.setAutoFillBackground(False)
        self.btn_ON.setObjectName("btn_ON")
        self.label_ITV_B = QtWidgets.QCheckBox(self.centralwidget)
        self.label_ITV_B.setGeometry(QtCore.QRect(30, 90, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setKerning(True)
        self.label_ITV_B.setFont(font)
        self.label_ITV_B.setChecked(False)
        self.label_ITV_B.setObjectName("label_ITV_B")
        self.label_ITV_A = QtWidgets.QCheckBox(self.centralwidget)
        self.label_ITV_A.setGeometry(QtCore.QRect(30, 30, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setKerning(True)
        self.label_ITV_A.setFont(font)
        self.label_ITV_A.setChecked(False)
        self.label_ITV_A.setObjectName("label_ITV_A")
        self.label_ITV_C = QtWidgets.QCheckBox(self.centralwidget)
        self.label_ITV_C.setGeometry(QtCore.QRect(30, 150, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setKerning(True)
        self.label_ITV_C.setFont(font)
        self.label_ITV_C.setChecked(False)
        self.label_ITV_C.setObjectName("label_ITV_C")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Creating button responses:
        self.btn_ON.clicked.connect(lambda:self.button_response(self.btn_ON))
        self.btn_OFF.clicked.connect(lambda:self.button_response(self.btn_OFF))
        self.btn_exit.clicked.connect(lambda:self.button_response(self.btn_exit))
        
    # Creating checkbox responses:

    # Connect
        self.label_ITV_A.stateChanged.connect(lambda state, x=1:self.check_connection(self.label_ITV_A,x))
        self.label_ITV_B.stateChanged.connect(lambda state, x=2:self.check_connection(self.label_ITV_B,x))
        self.label_ITV_C.stateChanged.connect(lambda state, x=3:self.check_connection(self.label_ITV_C,x))

    # Update:
        self.my_timer = QtCore.QTimer()
        self.my_timer.timeout.connect(self.update_status)
        self.my_timer.start(1000) #1 sec interval

        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_exit.setText(_translate("MainWindow", "Quit"))
        self.btn_ON.setText(_translate("MainWindow", "HIGH"))
        self.btn_OFF.setText(_translate("MainWindow", "LOW"))
        self.label_ITV_B.setText(_translate("MainWindow", " ITV 2 (psi): "))
        self.label_ITV_A.setText(_translate("MainWindow", " ITV 1 (psi): "))
        self.label_ITV_C.setText(_translate("MainWindow", " ITV 3 (psi): "))

    def btntest(self,b,x):
        if x == 1:
            print(str(x))
            if b.isChecked() == True:
                print(b.text()+" is checked")
                self.label_ITV_A.setText("ITV 1 is ON!")
            else:
                print(b.text()+" is not checked")
                self.label_ITV_A.setText("ITV 1 is OFF!")
        elif x == 2:
            print(str(x))
            if b.isChecked() == True:
                print(b.text()+" is checked")
                self.label_ITV_B.setText("ITV 2 is ON!")
            else:
                print(b.text()+" is not checked")
                self.label_ITV_B.setText("ITV 2 is OFF!")
        elif x == 3:
            print(str(x))
            if b.isChecked() == True:
                print(b.text()+" is checked")
                self.label_ITV_C.setText("ITV 3 is ON!")
            else:
                print(b.text()+" is not checked")
                self.label_ITV_C.setText("ITV 3 is OFF!")

    def button_response(self,b):
        if b.text() == "Quit":
            print("quitting...")
            sys.exit(app.exec_())
        if b.text() == "HIGH":
            value = 4095
            print(str(value))
        if b.text() == "LOW":
            value = 0
            print(str(value))
        if C_A != 1:
            print("Attempting to write")
            SetPoint = value
            x = SetPoint.to_bytes(2, "little") #change to bytes
            data = pyeip.struct.pack("BB", x[0], x[1])
            if C_A != 1:
                print("Write to 1")
                r = C_A.setAttrSingle(0x64, 0x64, 0x03, data) #write to ITV
                if r[0] == 0:
                    print("Wrote!")
                else:
                    print("Failed to write")
                r = C_A.getAttrSingle(0x96, 0x96, 0x03)
                print(r[1])
        if C_B != 1:
            print("Attempting to write")
            SetPoint = value
            x = SetPoint.to_bytes(2, "little") #change to bytes
            data = pyeip.struct.pack("BB", x[0], x[1])
            if C_B != 1:
                print("Write to 2")
                r = C_B.setAttrSingle(0x64, 0x64, 0x03, data) #write to ITV
                if r[0] == 0:
                    print("Wrote!")
                else:
                    print("Failed to write")
                r = C_B.getAttrSingle(0x96, 0x96, 0x03)
                print(r[1])
        if C_C != 1:
            print("Attempting to write")
            SetPoint = value
            x = SetPoint.to_bytes(2, "little") #change to bytes
            data = pyeip.struct.pack("BB", x[0], x[1])
            if C_C != 1:
                print("Write to 3")
                r = C_C.setAttrSingle(0x64, 0x64, 0x03, data) #write to ITV
                if r[0] == 0:
                    print("Wrote!")
                else:
                    print("Failed to write")
                r = C_C.getAttrSingle(0x96, 0x96, 0x03)
                print(r[1])

    def check_connection(self,c,ITV):
        if c.isChecked() == True:
            if ITV == 1:
                print("Attempting to connect...")
                try:
                    global EIP_1, C_A
                    EIP_1= pyeip.EtherNetIP(hostname1)
                    C_A = EIP_1.explicit_conn(hostname1)
                    print(C_A)
                except TimeoutError:
                    C_A = 1
            elif ITV == 2:
                print("Attempting to connect...")
                try:
                    global EIP_2, C_B
                    EIP_2= pyeip.EtherNetIP(hostname2)
                    C_B = EIP_2.explicit_conn(hostname2)
                    print(C_B)
                except TimeoutError:
                    C_B = 1
            elif ITV == 3:
                print("Attempting to connect...")
                try:
                    global EIP_3, C_C
                    EIP_3= pyeip.EtherNetIP(hostname3)
                    C_C = EIP_3.explicit_conn(hostname3)
                    print(C_C)
                except TimeoutError:
                    C_C = 1
                    
        else:
            print("Not Connected")
            if ITV == 1:
                C_A = 1
            elif ITV == 2:
                C_B = 1
            elif ITV == 3:
                C_C = 1

    def update_status(self):
        if C_A != 1:
            r = C_A.getAttrSingle(0x96, 0x96, 0x03)
            print(r[1])
            if 0 == r[0]:
                print(int.from_bytes(r[1],"little"))
                if(r[1][-2:] == b'\x00\x00'):
                    pressure = int.from_bytes(r[1],"little") #in counts
                    pressure = pressure / 31.37 #convert to psi
                    pressure = round(pressure, 3)
                    print(pressure)
                    self.label_ITV_A.setText("ITV 1 (psi): " + str(pressure))
                else:
                    self.label_ITV_A.setText("ITV 1 (psi): Error Detected")
        else:
            print("C_A Disconnected")
                    
        if C_B != 1:
            r = C_B.getAttrSingle(0x96, 0x96, 0x03)
            print(r[1])
            if 0 == r[0]:
                print(int.from_bytes(r[1],"little"))
                if(r[1][-2:] == b'\x00\x00'):
                    pressure = int.from_bytes(r[1],"little") #in counts
                    pressure = pressure / 31.37 #convert to psi
                    pressure = round(pressure, 3)
                    print(pressure)
                    self.label_ITV_B.setText("ITV 2 (psi): " + str(pressure))
                else:
                    self.label_ITV_B.setText("ITV 2 (psi): Error Detected")
        else:
            print("C_B Disconnected")
            
        if C_C != 1:
            r = C_C.getAttrSingle(0x96, 0x96, 0x03)
            print(r[1])
            if 0 == r[0]:
                print(int.from_bytes(r[1],"little"))
                if(r[1][-2:] == b'\x00\x00'):
                    pressure = int.from_bytes(r[1],"little") #in counts
                    pressure = pressure / 31.37 #convert to psi
                    pressure = round(pressure, 3)
                    print(pressure)
                    self.label_ITV_C.setText("ITV 3 (psi): " + str(pressure))
                else:
                    self.label_ITV_C.setText("ITV 3 (psi): Error Detected")
        else:
            print("C_C Disconnected")

if __name__ == "__main__":
    import sys
    print("loop")
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
